server:
  name: "valheim-server"
provider:
  name: hetzner
  settings:
    location: nbg1
    plan: cpx32
game:
  name: valheim
  settings:
    world: "my_valheim_world"
    password: "very_secure_password"
    thunderstore_code: "019cf113-4729-c139-63ac-ea85dafcffd6"
